### ISSUE TITLE
Please rename the CurseForge project

### ISSUE THREAD

**Issue by funkydude** [excorp/BigWigs_Voice_Korean#1]
Hello,

Could you please rename the project on CurseForge so that "KR" becomes "Korean"?
The full project name would end up looking like `BigWigs Voice (Korean)`

We have many English people installing this by accident as they don't understand what "KR" means.
Thank you!

**Comment by excorp** [comment]
I didn't realize that had happened. 
Thank you so much for your great addon, I changed the name immediately.

**Comment by funkydude** [comment]
Thanks!
